import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { DetectedProject } from "./detect.js";

/** Per-project directories under `~/.ctxd/projects/<id>/`. */
export const PROJECT_SUBDIRECTORIES = ["sessions", "snapshots", "memory"] as const;

export interface ProjectStorage {
  readonly dir: string;
  readonly files: readonly string[];
}

function describe(value: string | null): string {
  return value ?? "not detected";
}

function projectDocument(project: DetectedProject): string {
  return `# ${project.name}

- id: ${project.id}
- root: ${project.root}
- vcs: ${describe(project.vcs)}
- runtime: ${describe(project.runtime)}
- language: ${describe(project.language)}
- package manager: ${describe(project.packageManager)}
- framework: ${describe(project.framework)}

Detected from: ${project.evidence.length > 0 ? project.evidence.join(", ") : "no manifest files found"}

This file is generated by \`ctxd init\`. Notes added below the line are
preserved by hand only — re-running init rewrites the section above.
`;
}

function stackDocument(project: DetectedProject): string {
  const rows = [
    ["Runtime", describe(project.runtime)],
    ["Language", describe(project.language)],
    ["Package manager", describe(project.packageManager)],
    ["Framework", describe(project.framework)],
  ];

  return `# Stack

| Aspect | Value |
|--------|-------|
${rows.map(([key, value]) => `| ${key} | ${value} |`).join("\n")}

Every value above was read from a real file in the repository. Detection never
infers a stack from directory names.

Evidence:

${project.evidence.length > 0 ? project.evidence.map((file) => `- ${file}`).join("\n") : "- none found"}
`;
}

function gitDocument(project: DetectedProject): string {
  const { git } = project;
  if (git.insideWorkTree !== true) {
    return `# Git

Not a Git repository.
`;
  }

  const commits = git.recentCommits ?? [];
  const changes = git.changes ?? [];

  return `# Git

- branch: ${git.branch ?? "unknown"}
- root: ${git.root ?? project.root}
- root commit: ${git.rootCommit ?? "none"}
- uncommitted changes: ${changes.length}

## Recent commits

${
  commits.length === 0
    ? "No commits."
    : commits
        .map((commit) => `- \`${commit.hash.slice(0, 8)}\` ${commit.subject} — ${commit.author}`)
        .join("\n")
}

Git remains the source of truth for repository history; this file is a
snapshot taken at init time, not a replacement.
`;
}

/**
 * Instructions for AI workers.
 *
 * Claude Code and Cursor share one ctxd project memory — neither owns it — so
 * both receive the same guidance. These describe only what ctxd can actually
 * do today; tools that arrive in a later phase are not advertised here.
 */
function agentInstructions(project: DetectedProject): string {
  return `# Working on ${project.name} with ctxd

ctxd is the persistent engineering layer for this project. It holds project
knowledge and builds the minimum useful context for a task. It is the source of
truth for project memory: you do not own it, and neither does any other worker.

## Before starting a complex task

Ask ctxd for context instead of reading the repository yourself:

- \`ctx_context_build\` with the task you are about to do — returns the files,
  rules and decisions that matter, plus a receipt explaining each one
- \`ctx_project_summary\` — the stack and the binding rules
- \`ctx_decision_get\` — check whether a decision already governs your approach

Do not request the entire repository. The point of the context firewall is that
you do not have to, and a large context makes you worse at the task, not better.

Expand deliberately when you need more:

- \`ctx_search\` returns summaries with the cost of fetching each result
- \`ctx_get\` fetches one memory in full
- \`ctx_file_search\` / \`ctx_file_get\` for files
- \`ctx_history\` for recent commits

## Rules are binding

A rule marked P0 constrains the change even when the tests pass without it. If
a rule appears to be wrong, say so — do not quietly work around it.

## After meaningful work

Record what a future session could not infer from the code: a decision and its
reason, a constraint you discovered, a bug and its cause.

Use \`ctx_memory_save\` with source \`worker_statement\`. Your conclusions are
recorded with visible confidence and will never override something the
developer stated. If your finding contradicts an existing rule, ctxd will
refuse the write — raise the conflict with the developer rather than trying to
overwrite it.

## Without the CLI

Every tool above has a command-line equivalent:

\`\`\`bash
ctxd context --task "..." --dir ${project.root}
ctxd search "..." --dir ${project.root}
ctxd memory add --title "..." --content "..." --dir ${project.root}
\`\`\`

## What ctxd does not do

It does not run your tests, edit your code, or talk to any model. Every command
is local and deterministic.
`;
}

/** Registration snippets for the workers that can talk to ctxd today. */
function mcpSetup(project: DetectedProject): string {
  return `# Connecting a worker to ctxd

ctxd exposes its services over the Model Context Protocol. Every tool calls the
same code as the CLI — there is no second implementation to drift.

## Claude Code

\`\`\`bash
claude mcp add ctxd -- ctxd mcp --dir "${project.root}"
\`\`\`

## Cursor, and other MCP clients

Add to the client's MCP configuration:

\`\`\`json
{
  "mcpServers": {
    "ctxd": {
      "command": "ctxd",
      "args": ["mcp", "--dir", ${JSON.stringify(project.root)}]
    }
  }
}
\`\`\`

Both workers then read and write the same project memory. Neither owns it.

## Available tools

| Tool | Purpose |
|------|---------|
| \`ctx_status\` | ctxd state and whether this directory is registered |
| \`ctx_project_summary\` | Stack, indexed file count, binding rules |
| \`ctx_context_build\` | Minimum useful context for a task, with a receipt |
| \`ctx_search\` | Search project memory; returns summaries |
| \`ctx_get\` | Fetch one memory in full |
| \`ctx_decision_get\` | Decisions already taken |
| \`ctx_file_search\` | Find indexed files by path |
| \`ctx_file_get\` | Read one file, confined to the project root |
| \`ctx_history\` | Recent commits |
| \`ctx_memory_save\` | Record a decision, constraint or bug |
| \`ctx_memory_update\` | Revise a memory, superseding the old version |

Task, checkpoint and handoff tools are not offered yet: those services do not
exist, and a tool that cannot do what its name promises is worse than no tool.
`;
}

/**
 * Create the project's directory under `~/.ctxd/projects/` and write its
 * generated documents.
 */
export function writeProjectStorage(
  projectsDir: string,
  project: DetectedProject,
): ProjectStorage {
  const dir = join(projectsDir, project.id);
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  for (const name of PROJECT_SUBDIRECTORIES) {
    mkdirSync(join(dir, name), { recursive: true, mode: 0o700 });
  }

  const documents: readonly (readonly [string, string])[] = [
    ["project.md", projectDocument(project)],
    ["stack.md", stackDocument(project)],
    ["git.md", gitDocument(project)],
    ["agent-instructions.md", agentInstructions(project)],
    ["mcp-setup.md", mcpSetup(project)],
  ];

  for (const [name, content] of documents) {
    writeFileSync(join(dir, name), content, { mode: 0o600 });
  }

  return { dir, files: documents.map(([name]) => name) };
}
